# Reload tmux config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Prefix
set -g prefix C-s
set -g mouse off
set-option -g status-position top
set -g base-index 1
set -g mode-keys vi

# Status bar
set -g status-right-length 100
set -g status-left-length 100
set -g status-style "#{?client_prefix,bg=cyan fg=black bold,bg=yellow fg=cyan bold}"
set -g status-left ""
set -g status-right "#{?client_prefix,#[fg=cyan bold bg=black]   🔧  PREFIX  🔧   #[default], } #[fg=black bold, bg=magenta]  Session: #S  "
set -g window-status-style "#{?client_prefix,bg=magenta fg=black,bg=yellow fg=cyan}"
set -g window-status-current-style "#{?client_prefix,bg=black fg=cyan bold,bg=yellow fg=cyan bold}"

# Plugins
set -g @plugin "tmux-plugins/tpm"

# Initialize TPM (keep at bottom)
run "~/.config/tmux/plugins/tpm/tpm"
