exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = ! hyprland-toggle-enabled waybar-off && uwsm-app -- waybar
exec-once = uwsm-app -- elephant
exec-once = uwsm-app -- walker --gapplication-service
exec-once = uwsm-app -- mako
exec-once = uwsm-app -- waypaper --restore

exec-once = /usr/libexec/polkit-mate-authentication-agent-1

