# Window rules

# Suppress maximize
windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

# Fix XWayland drags
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# Browsers - force tile
windowrule = tile on, match:class ^(vivaldi-stable)$
windowrule = tile on, match:class ^(Brave-browser)$
windowrule = tile on, match:class ^(Chromium)$
windowrule = tile on, match:class ^(discord)$

# Float settings apps
windowrule = float on, size 700 600, center on, pin on, match:class (.*org.pulseaudio.pavucontrol.*)
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:class ^(me.adriel.*)$
windowrule = float on, size 700 600, center on, match:class (org.gnome.Calculator)
windowrule = float on, size 700 600, center on, match:class ^(qalculate-gtk)$
windowrule = float on, size 900 600, move 10% 20%, pin on, match:class (nwg-displays)
windowrule = float on, size 1000 700, center on, match:class (io.missioncenter.MissionCenter)
windowrule = float on, size 1000 700, center on, match:class ^(waypaper)$

# Float file pickers
windowrule = float on, center on, match:class xdg-desktop-portal-gtk, match:title ^(Open.*Files?|Save.*Files?|All Files|Save)

# Browser Picture in Picture
windowrule = float on, pin on, move 76.5% 78%, no_shadow on, opaque on, border_size 0, rounding 0, keep_aspect_ratio on, match:title ^(Picture[- ]in[- ]picture)$

# mpv
windowrule = float on, no_shadow on, opaque on, border_size 0, rounding 0, keep_aspect_ratio on, match:class ^(mpv)$

# Hyprland Share Picker
windowrule = float on, pin on, center on, size 600 400, match:class (hyprland-share-picker)

# Hyprland-run
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

# XWayland scaling
xwayland {
    force_zero_scaling = true
}
