# Hyprland config

# Monitors
source = ~/.config/hypr/conf/monitors.conf

# Programs
source = ~/.config/hypr/conf/programs.conf

# Autostart
source = ~/.config/hypr/conf/autostart.conf

# Environment
source = ~/.config/hypr/conf/env.conf

# Look and Feel
source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/decoration.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/dwindle.conf
source = ~/.config/hypr/conf/misc.conf
source = ~/.config/hypr/conf/keyboard.conf

# Input
source = ~/.config/hypr/conf/input.conf

# Keybindings
source = ~/.config/hypr/conf/keybindings.conf

# Window Rules
source = ~/.config/hypr/conf/windowrules.conf

