general {
    ignore_empty_input = true
}

background {
    monitor =
    path = ~/pictures/wallpapers/wallhaven-zpq1dg.jpg	# Still in progress lol
    blur_passes = 3
    blur_size = 7
}

input-field {
    monitor =
    size = 400, 50
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    inner_color = rgba(33, 52, 66, 0.8)
    font_color = rgba(214, 226, 238, 1)
    font_family = MonaspiceNe Nerd Font
    outer_color = rgba(137, 180, 250, 0.5)
    outline_thickness = 3
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Input Password...</i>
    hide_input = false
    rounding = 10
    check_color = rgba(137, 180, 250, 0.8)
    fail_color = rgba(243, 139, 168, 0.8)
    fail_text = <i> <b>($ATTEMPTS)</b></i>
    position = 0, -20
    halign = center
    valign = center
    shadow_passes = 10
    shadow_size = 20
    shadow_color = rgba(0, 0, 0, 0.5)
    shadow_boost = 1.6
}

label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(214, 226, 238, 1)
    font_size = 70
    font_family = MonaspiceNe Nerd Font
    position = -50, 20
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
    shadow_color = rgba(0, 0, 0, 0.5)
}

label {
    monitor =
    text = $USER
    color = rgba(214, 226, 238, 1)
    font_size = 20
    font_family = MonaspiceNe Nerd Font
    position = -50, 120
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
    shadow_color = rgba(0, 0, 0, 0.5)
}
